// Auto generated via cli/images.build.js

export const LEVEL5DATA = [
    {
        "name": "background",
        "gridCellWidth": 8,
        "gridCellHeight": 8,
        "gridCellsX": 12,
        "gridCellsY": 12,
        "tileset": "tileset",
        "data": [
            15,
            -1,
            13,
            12,
            13,
            12,
            5,
            11,
            5,
            13,
            15,
            12,
            12,
            -1,
            13,
            12,
            12,
            13,
            12,
            12,
            12,
            16,
            12,
            14,
            13,
            -1,
            0,
            28,
            2,
            28,
            4,
            28,
            27,
            2,
            2,
            13,
            16,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            2,
            -1,
            -1,
            -1,
            12,
            12,
            -1,
            4,
            4,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            4,
            12,
            12,
            -1,
            -1,
            1,
            4,
            0,
            -1,
            -1,
            2,
            -1,
            0,
            15,
            13,
            -1,
            4,
            -1,
            2,
            -1,
            -1,
            -1,
            -1,
            1,
            0,
            16,
            12,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            4,
            -1,
            13,
            13,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            14,
            15,
            -1,
            -1,
            8,
            10,
            -1,
            -1,
            -1,
            8,
            -1,
            -1,
            13,
            13,
            13,
            13,
            22,
            22,
            12,
            14,
            15,
            22,
            19,
            22,
            15,
            28,
            27,
            3,
            -1,
            2,
            1,
            1,
            3,
            4,
            1,
            3,
            28
        ]
    },
    {
        "name": "collision",
        "gridCellWidth": 8,
        "gridCellHeight": 8,
        "gridCellsX": 12,
        "gridCellsY": 12,
        "entities": [
            {
                "name": "platform",
                "id": 1,
                "x": 0,
                "y": 0,
                "width": 8,
                "height": 80
            },
            {
                "name": "platform",
                "id": 2,
                "x": 88,
                "y": 0,
                "width": 8,
                "height": 80
            },
            {
                "name": "platform",
                "id": 8,
                "x": 0,
                "y": 80,
                "width": 96,
                "height": 8
            }
        ]
    },
    {
        "name": "entities",
        "gridCellWidth": 8,
        "gridCellHeight": 8,
        "gridCellsX": 12,
        "gridCellsY": 12,
        "entities": [
            {
                "name": "player",
                "id": 10,
                "x": 8,
                "y": 8,
                "width": 8,
                "height": 8
            },
            {
                "name": "frog",
                "id": 11,
                "x": 72,
                "y": 64,
                "width": 16,
                "height": 16
            }
        ]
    }
];