// Auto generated via cli/images.build.js

export const LEVEL3DATA = [
    {
        "name": "background",
        "gridCellWidth": 8,
        "gridCellHeight": 8,
        "gridCellsX": 12,
        "gridCellsY": 12,
        "tileset": "tileset",
        "data": [
            13,
            13,
            12,
            12,
            16,
            12,
            12,
            12,
            13,
            13,
            14,
            12,
            12,
            15,
            12,
            13,
            12,
            16,
            12,
            12,
            12,
            16,
            12,
            16,
            -1,
            -1,
            -1,
            2,
            25,
            3,
            24,
            -1,
            28,
            4,
            28,
            1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            3,
            -1,
            4,
            -1,
            -1,
            10,
            -1,
            -1,
            -1,
            3,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            18,
            21,
            12,
            -1,
            2,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            12,
            28,
            24,
            -1,
            -1,
            -1,
            2,
            13,
            0,
            -1,
            -1,
            12,
            13,
            3,
            2,
            5,
            11,
            11,
            11,
            11,
            5,
            11,
            11,
            12,
            16,
            -1,
            -1,
            23,
            23,
            23,
            23,
            17,
            23,
            17,
            23,
            13,
            2,
            -1,
            -1,
            1,
            28,
            3,
            -1,
            -1,
            27,
            2,
            1,
            1,
            -1,
            -1,
            -1,
            3,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            4,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1
        ]
    },
    {
        "name": "collision",
        "gridCellWidth": 8,
        "gridCellHeight": 8,
        "gridCellsX": 12,
        "gridCellsY": 12,
        "entities": [
            {
                "name": "platform",
                "id": 1,
                "x": -8,
                "y": 0,
                "width": 8,
                "height": 64
            },
            {
                "name": "platform",
                "id": 2,
                "x": 104,
                "y": -8,
                "width": 8,
                "height": 80
            },
            {
                "name": "platform",
                "id": 8,
                "x": 0,
                "y": 40,
                "width": 24,
                "height": 32
            },
            {
                "name": "platform",
                "id": 10,
                "x": 24,
                "y": 64,
                "width": 64,
                "height": 8
            },
            {
                "name": "platform",
                "id": 14,
                "x": 88,
                "y": 48,
                "width": 16,
                "height": 24
            },
            {
                "name": "platform",
                "id": 15,
                "x": 56,
                "y": 48,
                "width": 8,
                "height": 8
            }
        ]
    },
    {
        "name": "entities",
        "gridCellWidth": 8,
        "gridCellHeight": 8,
        "gridCellsX": 12,
        "gridCellsY": 12,
        "entities": [
            {
                "name": "player",
                "id": 10,
                "x": 0,
                "y": 32,
                "width": 8,
                "height": 8
            },
            {
                "name": "torch",
                "id": 11,
                "x": 32,
                "y": 32,
                "width": 8,
                "height": 8
            },
            {
                "name": "hurt",
                "id": 12,
                "x": 24,
                "y": 56,
                "width": 64,
                "height": 8
            },
            {
                "name": "torch",
                "id": 13,
                "x": 72,
                "y": 24,
                "width": 8,
                "height": 8
            },
            {
                "name": "exit",
                "id": 14,
                "x": 96,
                "y": 16,
                "width": 8,
                "height": 32
            }
        ]
    },
    {
        "name": "texts",
        "gridCellWidth": 8,
        "gridCellHeight": 8,
        "gridCellsX": 12,
        "gridCellsY": 12,
        "entities": [
            {
                "name": "text",
                "id": 0,
                "x": 24,
                "y": 80,
                "width": 8,
                "height": 8,
                "values": {
                    "text": "'J' to Swing",
                    "name": "",
                    "visible": true
                }
            }
        ]
    }
];