// Auto generated via cli/images.build.js

export const LEVEL1DATA = [
    {
        "name": "background",
        "gridCellWidth": 8,
        "gridCellHeight": 8,
        "gridCellsX": 12,
        "gridCellsY": 12,
        "tileset": "tileset",
        "data": [
            13,
            16,
            13,
            12,
            16,
            12,
            12,
            12,
            13,
            13,
            14,
            12,
            12,
            15,
            16,
            12,
            12,
            16,
            12,
            12,
            12,
            16,
            12,
            16,
            4,
            -1,
            -1,
            2,
            25,
            3,
            24,
            12,
            28,
            4,
            28,
            12,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            3,
            -1,
            2,
            -1,
            9,
            -1,
            -1,
            7,
            9,
            -1,
            -1,
            -1,
            -1,
            8,
            -1,
            -1,
            18,
            18,
            22,
            16,
            22,
            0,
            0,
            0,
            22,
            15,
            18,
            18,
            4,
            28,
            3,
            24,
            2,
            1,
            1,
            4,
            4,
            1,
            4,
            1,
            1,
            3,
            3,
            2,
            -1,
            -1,
            3,
            4,
            4,
            1,
            -1,
            0,
            -1,
            4,
            -1,
            -1,
            -1,
            -1,
            4,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1
        ]
    },
    {
        "name": "collision",
        "gridCellWidth": 8,
        "gridCellHeight": 8,
        "gridCellsX": 12,
        "gridCellsY": 12,
        "entities": [
            {
                "name": "platform",
                "id": 1,
                "x": -8,
                "y": 0,
                "width": 8,
                "height": 48
            },
            {
                "name": "platform",
                "id": 2,
                "x": 96,
                "y": 0,
                "width": 8,
                "height": 48
            },
            {
                "name": "platform",
                "id": 8,
                "x": 0,
                "y": 40,
                "width": 40,
                "height": 8
            },
            {
                "name": "platform",
                "id": 14,
                "x": 56,
                "y": 16,
                "width": 8,
                "height": 8
            },
            {
                "name": "platform",
                "id": 15,
                "x": 88,
                "y": 16,
                "width": 8,
                "height": 8
            },
            {
                "name": "platform",
                "id": 16,
                "x": 64,
                "y": 40,
                "width": 32,
                "height": 8
            }
        ]
    },
    {
        "name": "entities",
        "gridCellWidth": 8,
        "gridCellHeight": 8,
        "gridCellsX": 12,
        "gridCellsY": 12,
        "entities": [
            {
                "name": "player",
                "id": 10,
                "x": 8,
                "y": 32,
                "width": 8,
                "height": 8
            },
            {
                "name": "exit",
                "id": 11,
                "x": 0,
                "y": 88,
                "width": 96,
                "height": 8
            },
            {
                "name": "fireflies",
                "id": 12,
                "x": 24,
                "y": 16,
                "width": 24,
                "height": 24
            },
            {
                "name": "alice",
                "id": 13,
                "x": 72,
                "y": 24,
                "width": 16,
                "height": 16
            },
            {
                "name": "fallingTiles",
                "id": 14,
                "x": 40,
                "y": 32,
                "width": 24,
                "height": 24
            }
        ]
    },
    {
        "name": "texts",
        "gridCellWidth": 8,
        "gridCellHeight": 8,
        "gridCellsX": 12,
        "gridCellsY": 12,
        "entities": [
            {
                "name": "text",
                "id": 0,
                "x": 0,
                "y": 80,
                "width": 8,
                "height": 8,
                "values": {
                    "text": "'A' and 'D' to Move",
                    "name": "",
                    "visible": true
                }
            }
        ]
    }
];