// Auto generated via cli/images.build.js

export const LEVEL6DATA = [
    {
        "name": "background",
        "gridCellWidth": 8,
        "gridCellHeight": 8,
        "gridCellsX": 12,
        "gridCellsY": 12,
        "tileset": "tileset",
        "data": [
            15,
            14,
            13,
            12,
            13,
            12,
            12,
            12,
            15,
            13,
            15,
            12,
            12,
            15,
            13,
            12,
            12,
            13,
            12,
            12,
            12,
            16,
            12,
            14,
            4,
            28,
            0,
            2,
            -1,
            -1,
            28,
            2,
            28,
            4,
            28,
            25,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            3,
            9,
            -1,
            -1,
            8,
            8,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            10,
            21,
            18,
            18,
            22,
            22,
            12,
            13,
            12,
            22,
            19,
            22,
            21,
            28,
            27,
            3,
            -1,
            2,
            1,
            1,
            3,
            4,
            1,
            3,
            28,
            3,
            3,
            3,
            -1,
            -1,
            -1,
            3,
            3,
            -1,
            -1,
            4,
            0,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1
        ]
    },
    {
        "name": "collision",
        "gridCellWidth": 8,
        "gridCellHeight": 8,
        "gridCellsX": 12,
        "gridCellsY": 12,
        "entities": [
            {
                "name": "platform",
                "id": 1,
                "x": -8,
                "y": 0,
                "width": 8,
                "height": 48
            },
            {
                "name": "platform",
                "id": 2,
                "x": 96,
                "y": 0,
                "width": 8,
                "height": 48
            },
            {
                "name": "platform",
                "id": 8,
                "x": 0,
                "y": 40,
                "width": 96,
                "height": 8
            }
        ]
    },
    {
        "name": "entities",
        "gridCellWidth": 8,
        "gridCellHeight": 8,
        "gridCellsX": 12,
        "gridCellsY": 12,
        "entities": [
            {
                "name": "player",
                "id": 10,
                "x": 8,
                "y": 32,
                "width": 8,
                "height": 8
            },
            {
                "name": "alice",
                "id": 13,
                "x": 72,
                "y": 24,
                "width": 16,
                "height": 16
            }
        ]
    },
    {
        "name": "texts",
        "gridCellWidth": 8,
        "gridCellHeight": 8,
        "gridCellsX": 12,
        "gridCellsY": 12,
        "entities": [
            {
                "name": "text",
                "id": 0,
                "x": 32,
                "y": 64,
                "width": 8,
                "height": 8,
                "values": {
                    "text": "The End",
                    "name": "",
                    "visible": false
                }
            },
            {
                "name": "text",
                "id": 1,
                "x": 24,
                "y": 80,
                "width": 8,
                "height": 8,
                "values": {
                    "text": "'R' to Restart",
                    "name": "",
                    "visible": false
                }
            }
        ]
    }
];