// Auto generated via cli/images.build.js

export const LEVEL2DATA = [
    {
        "name": "background",
        "gridCellWidth": 8,
        "gridCellHeight": 8,
        "gridCellsX": 12,
        "gridCellsY": 12,
        "tileset": "tileset",
        "data": [
            3,
            0,
            0,
            12,
            16,
            12,
            14,
            12,
            12,
            12,
            13,
            12,
            -1,
            4,
            4,
            4,
            1,
            1,
            25,
            3,
            28,
            12,
            15,
            13,
            -1,
            -1,
            -1,
            2,
            0,
            -1,
            -1,
            3,
            4,
            4,
            24,
            2,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            2,
            -1,
            9,
            -1,
            8,
            9,
            -1,
            -1,
            4,
            -1,
            -1,
            -1,
            -1,
            -1,
            18,
            18,
            19,
            22,
            -1,
            2,
            2,
            0,
            -1,
            -1,
            -1,
            -1,
            12,
            28,
            25,
            12,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            15,
            13,
            3,
            2,
            12,
            -1,
            -1,
            -1,
            10,
            -1,
            -1,
            -1,
            12,
            3,
            -1,
            2,
            15,
            11,
            5,
            21,
            22,
            22,
            20,
            12,
            13,
            -1,
            -1,
            -1,
            23,
            17,
            23,
            23,
            3,
            27,
            0,
            0,
            12,
            -1,
            -1,
            -1,
            3,
            1,
            -1,
            -1,
            -1,
            -1,
            2,
            4,
            4,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1
        ]
    },
    {
        "name": "collision",
        "gridCellWidth": 8,
        "gridCellHeight": 8,
        "gridCellsX": 12,
        "gridCellsY": 12,
        "entities": [
            {
                "name": "platform",
                "id": 1,
                "x": -8,
                "y": 0,
                "width": 8,
                "height": 56
            },
            {
                "name": "platform",
                "id": 2,
                "x": 104,
                "y": -8,
                "width": 8,
                "height": 88
            },
            {
                "name": "platform",
                "id": 5,
                "x": 88,
                "y": 48,
                "width": 16,
                "height": 32
            },
            {
                "name": "platform",
                "id": 8,
                "x": 0,
                "y": 40,
                "width": 32,
                "height": 8
            },
            {
                "name": "platform",
                "id": 9,
                "x": 24,
                "y": 48,
                "width": 8,
                "height": 24
            },
            {
                "name": "platform",
                "id": 10,
                "x": 48,
                "y": 64,
                "width": 40,
                "height": 8
            },
            {
                "name": "platform",
                "id": 15,
                "x": 16,
                "y": 72,
                "width": 48,
                "height": 16
            }
        ]
    },
    {
        "name": "entities",
        "gridCellWidth": 8,
        "gridCellHeight": 8,
        "gridCellsX": 12,
        "gridCellsY": 12,
        "entities": [
            {
                "name": "player",
                "id": 10,
                "x": 8,
                "y": 8,
                "width": 8,
                "height": 8
            },
            {
                "name": "hurt",
                "id": 11,
                "x": 32,
                "y": 64,
                "width": 16,
                "height": 8
            },
            {
                "name": "exit",
                "id": 13,
                "x": 96,
                "y": 16,
                "width": 8,
                "height": 32
            },
            {
                "name": "totem",
                "id": 14,
                "x": 72,
                "y": 40,
                "width": 24,
                "height": 24,
                "values": {
                    "flipH": -1,
                    "attackTime": 3
                }
            }
        ]
    },
    {
        "name": "texts",
        "gridCellWidth": 8,
        "gridCellHeight": 8,
        "gridCellsX": 12,
        "gridCellsY": 12,
        "entities": [
            {
                "name": "text",
                "id": 0,
                "x": 24,
                "y": 80,
                "width": 8,
                "height": 8,
                "values": {
                    "text": "'K' to Jump",
                    "name": "",
                    "visible": true
                }
            },
            {
                "name": "text",
                "id": 1,
                "x": 24,
                "y": 88,
                "width": 8,
                "height": 8,
                "values": {
                    "text": "'J' to Attack",
                    "name": "",
                    "visible": true
                }
            }
        ]
    }
];